import style from './page.module.css'
import Nav from "./Nav/Nav"
export const metadata = {
  title: 'Enzo Lacuesta',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">      
      <body className={style.body}>
        <Nav></Nav>
        {children}
      </body>
    </html>
  )
}
